import re
from playwright.sync_api import Page, expect


def test_send_form_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("Unit test en")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/unittesten")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="I consent to the processing of personal data").locator("use").click()
    page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button").click()
    expect(page.locator("div").filter(has_text="Your data has been sent").nth(1)).to_be_visible()
    page.screenshot(path="mw_mentoren_scr/mwsendform.png")


def test_close_success_mw_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("Unit test en")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/unittesten")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="I consent to the processing of personal data").locator("use").click()
    page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button").click()
    page.screenshot(path="mw_mentoren_scr/mwclosesmwO.png")
    page.locator("//button[@class='CloseBtn_btn__ij9AH UseAlert_close_btn__JJTAr']").click()
    expect(page.locator("div").filter(has_text="Your data has been sent").nth(1)).to_be_hidden()
    page.screenshot(path="mw_mentoren_scr/mwclosesmwC.png")


def test_active_sendbtn_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("Unit test en")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/unittesten")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="I consent to the processing of personal data").locator("use").click()
    expect(page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button")).to_be_enabled()
    page.screenshot(path="mw_mentoren_scr/mwasendbtn.png")


def test_hover_sendbtn_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("Unit test en")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/unittesten")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="I consent to the processing of personal data").locator("use").click()
    page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button").hover()
    expect(page.locator("form").filter(has_text="Mentor registration on Baza")).to_be_enabled()
    page.screenshot(path="mw_mentoren_scr/mwhsendbtn.png")


def test_default_sendbtn_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    expect(page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button")).to_be_disabled()
    page.screenshot(path="mw_mentoren_scr/mwdefsendbtn.png")


def test_disabled_sendbtn_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("a")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/Unittesten")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="I consent to the processing of personal data").locator("use").click()
    expect(page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button")).to_be_disabled()
    page.screenshot(path="mw_mentoren_scr/mwdsendbtn.png")


def test_without_checkbox_mw_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("Unit test en")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/Unittesten")
    expect(page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button")).to_be_disabled()
    page.screenshot(path="mw_mentoren_scr/mwwithoutch.png")


def test_empty_form_mw_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).click()
    page.get_by_placeholder("Last Name").click()
    page.get_by_role("textbox", name="email@gmail.com").click()
    page.get_by_placeholder("+380 xx xxx xx xx").click()
    page.locator("//input[@id='discord']").click()
    page.get_by_placeholder("Link to profile").click()
    expect(page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button")).to_be_disabled()
    page.screenshot(path="mw_mentoren_scr/mwemptyform.png")


def test_title_mw_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    expect(page.locator("//div[@class='RegistrationFormModal_wrapper__bgALB']//h2")).to_have_text("Mentor registration on Baza Trainee Ukraine")
    page.screenshot(path="mw_mentoren_scr/mwtitle.png")


def test_close_mw_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    expect(page.locator("//div[@class='RegistrationFormModal_wrapper__bgALB']")).to_be_visible()
    page.screenshot(path="mw_mentoren_scr/mwclosevmw.png")
    page.locator("//button[@class='CloseBtn_btn__ij9AH RegistrationFormModal_closeButton__Wn1pT']").click()
    expect(page.locator("//div[@class='RegistrationFormModal_wrapper__bgALB']")).to_be_hidden()
    page.screenshot(path="mw_mentoren_scr/mwclosehmw.png")


def test_chb_specialization_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.locator("label").filter(has_text="UI/UX Designer").check()
    expect(page.locator("label").filter(has_text="UI/UX Designer")).to_be_checked()
    page.locator("label").filter(has_text="Frontend").check()
    expect(page.locator("label").filter(has_text="Frontend")).to_be_checked()
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    expect(page.locator("label").filter(has_text="QA Manual Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Backend").check()
    expect(page.locator("label").filter(has_text="Backend")).to_be_checked()
    page.locator("label").filter(has_text="Fullstack Engineer").check()
    expect(page.locator("label").filter(has_text="Fullstack Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Project Manager").check()
    expect(page.locator("label").filter(has_text="Project Manager")).to_be_checked()


def test_chb_consultation_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.locator("label").filter(has_text="-15.00").check()
    expect(page.locator("label").filter(has_text="-15.00")).to_be_checked()
    page.locator("label").filter(has_text="-18.00").check()
    expect(page.locator("label").filter(has_text="-18.00")).to_be_checked()
    page.locator("label").filter(has_text="-21.00").check()
    expect(page.locator("label").filter(has_text="-21.00")).to_be_checked()
    page.locator("label").filter(has_text="anytime").check()
    expect(page.locator("label").filter(has_text="anytime")).to_be_checked()


def test_send_form_without_agreement_en(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Become a mentor").click()
    page.get_by_role("textbox", name="First Name", exact=True).type("Unit test en")
    page.get_by_placeholder("Last Name").type("Unit test en")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittesten")
    page.get_by_placeholder("Link to profile").fill("https://www.linkedin.com/in/unittesten")
    page.get_by_text("-15.00").click()
    expect(page.locator("form").filter(has_text="Mentor registration on Baza").get_by_role("button")).to_be_disabled()
    page.screenshot(path="mw_mentoren_scr/mwsendformwithoutagr.png")