import re
from playwright.sync_api import Page, expect


def test_close_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH RegistrationFormModal_closeButton__Wn1pT']").click()
    expect(page.locator(".RegistrationFormModal_wrapper__bgALB")).to_be_hidden()
    page.screenshot(path="mw_screenshots/mw.png")


def test_title_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    expect(page.locator("form h2")).to_have_text("Registration for participation in the Baza Trainee Ukraine project")
    page.screenshot(path="mw_screenshots/titlemw.png")


def test_select_specialization(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.locator("label").filter(has_text="UI/UX Designer").check()
    expect(page.locator("label").filter(has_text="UI/UX Designer")).to_be_checked()
    page.locator("label").filter(has_text="Frontend").check()
    expect(page.locator("label").filter(has_text="Frontend")).to_be_checked()
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    expect(page.locator("label").filter(has_text="QA Manual Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Backend").check()
    expect(page.locator("label").filter(has_text="Backend")).to_be_checked()
    page.locator("label").filter(has_text="Fullstack Engineer").check()
    expect(page.locator("label").filter(has_text="Fullstack Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Project Manager").check()
    expect(page.locator("label").filter(has_text="Project Manager")).to_be_checked()


def test_select_availability_of_experience(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.locator("label").filter(has_text="Yes").check()
    expect(page.locator("label").filter(has_text="Yes")).to_be_checked()
    page.screenshot(path="mw_screenshots/yesexp.png")
    page.locator("label").filter(has_text="No").check()
    expect(page.locator("label").filter(has_text="No")).to_be_checked()
    page.screenshot(path="mw_screenshots/noexp.png")


def test_select_questionnaire(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.locator("label").filter(has_text="On the Baza Trainee Ukraine").check()
    expect(page.locator("label").filter(has_text="On the Baza Trainee Ukraine")).to_be_checked()
    page.locator("label").filter(has_text="On the Baza Educat Instagram").check()
    expect(page.locator("label").filter(has_text="On the Baza Educat Instagram")).to_be_checked()
    page.locator("label").filter(has_text="On the Baza Educat Facebook").check()
    expect(page.locator("label").filter(has_text="On the Baza Educat Facebook")).to_be_checked()
    page.locator("label").filter(has_text="in the Baza Go Telegram").check()
    expect(page.locator("label").filter(has_text="in the Baza Go Telegram")).to_be_checked()
    page.locator("label").filter(has_text="in a LinkedIn post").check()
    expect(page.locator("label").filter(has_text="in a LinkedIn post")).to_be_checked()


def test_rules_BazaTrainee_project_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_role("button", name="Read here").click()
    expect(page.locator("//div[@class='ModalDocumentPdf_wrapper___sx__']")).to_be_visible()
    page.screenshot(path="mw_screenshots/rules.png")
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    expect(page.locator("//div[@class='ModalDocumentPdf_wrapper___sx__']")).to_be_hidden()
    page.screenshot(path="mw_screenshots/closerulesmw.png")


def test_select_agreement(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.locator("label").filter(has_text="I agree").check()
    page.locator("label").filter(has_text="I consent to the processing").check()
    expect(page.locator("label").filter(has_text="I agree")).to_be_checked()
    expect(page.locator("label").filter(has_text="I consent to the processing")).to_be_checked()
    page.screenshot(path="mw_screenshots/agreement.png")


def test_active_send_btn_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_placeholder("First Name").type("Test")
    page.get_by_placeholder("Last Name").type("Test")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kyiv").type("Kharkiv")
    page.get_by_placeholder("Ukraine").type("Ukraine")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link to profile").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Yes").check()
    page.get_by_placeholder("Your answer").type("test text")
    page.locator("label").filter(has_text="On the Baza Trainee Ukraine").check()
    page.get_by_role("button", name="Read here").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    page.locator("label").filter(has_text="I agree").check()
    page.locator("label").filter(has_text="I consent to the processing").check()
    expect(page.get_by_role("button", name="Send")).to_be_enabled()
    page.screenshot(path="mw_screenshots/mwsendbtn.png")


def test_send_form_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_placeholder("First Name").type("Test")
    page.get_by_placeholder("Last Name").type("Test")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kyiv").type("Kharkiv")
    page.get_by_placeholder("Ukraine").type("Ukraine")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link to profile").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Yes").check()
    page.get_by_placeholder("Your answer").type("test text") #min 5 char
    page.locator("label").filter(has_text="On the Baza Trainee Ukraine").check()
    page.get_by_role("button", name="Read here").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    page.locator("label").filter(has_text="I agree").check()
    page.locator("label").filter(has_text="I consent to the processing").check()
    page.get_by_role("button", name="Send").click()
    expect(page.locator("div").filter(has_text="Your data has been sent").nth(1)).to_be_visible()
    page.screenshot(path="mw_screenshots/mwsendform.png")


def test_send_form_without_last_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_placeholder("First Name").type("Test")
    page.get_by_placeholder("Last Name").type("Test")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kyiv").type("Kharkiv")
    page.get_by_placeholder("Ukraine").type("Ukraine")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link to profile").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Yes").check()
    page.get_by_placeholder("Your answer").type("test text") #min 5 char
    page.locator("label").filter(has_text="On the Baza Trainee Ukraine").check()
    page.locator("label").filter(has_text="I agree").check()
    expect(page.get_by_role("button", name="Send")).to_be_disabled()
    page.screenshot(path="mw_screenshots/mwsendwithoutlast.png")


def test_send_form_without_last2_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_placeholder("First Name").type("Test")
    page.get_by_placeholder("Last Name").type("Test")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kyiv").type("Kharkiv")
    page.get_by_placeholder("Ukraine").type("Ukraine")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link to profile").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Yes").check()
    page.get_by_placeholder("Your answer").type("test text") #min 5 char
    page.locator("label").filter(has_text="On the Baza Trainee Ukraine").check()
    page.locator("label").filter(has_text="I consent to the processing").check()
    expect(page.get_by_role("button", name="Send")).to_be_disabled()
    page.screenshot(path="mw_screenshots/mwsendwithoutlast2.png")


def test_empty_form_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_placeholder("First Name").click()
    page.get_by_placeholder("Last Name").click()
    page.get_by_placeholder("email@gmail.com").click()
    page.get_by_placeholder("+380 xx xxx xx xx").click()
    page.get_by_placeholder("Kyiv").click()
    page.get_by_placeholder("Ukraine").click()
    page.locator("//input[@id='discord']").click()
    page.get_by_placeholder("Link to profile").click()
    page.get_by_placeholder("Your answer").click()
    expect(page.get_by_role("button", name="Send")).to_be_disabled()
    page.screenshot(path="mw_screenshots/mwemptyform.png")


def test_send_without_checkbox_mw(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("EN").click()
    page.get_by_role("banner").get_by_role("link", name="Internship").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Join the project").first.click()
    page.get_by_placeholder("First Name").type("Test")
    page.get_by_placeholder("Last Name").type("Test")
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kyiv").type("Kharkiv")
    page.get_by_placeholder("Ukraine").type("Ukraine")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link to profile").type("https://www.linkedin.com/in/test")
    page.get_by_placeholder("Your answer").type("test text") #min 5 char
    expect(page.get_by_role("button", name="Send")).to_be_disabled()
    page.screenshot(path="mw_screenshots/mwsendwithoutcheckbox.png")

