import re
from playwright.sync_api import Page, expect


def test_close_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH RegistrationFormModal_closeButton__Wn1pT']").click()
    expect(page.locator(".RegistrationFormModal_wrapper__bgALB")).to_be_hidden()
    page.screenshot(path="mwpl_screenshots/mw.png")


def test_title_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    expect(page.locator("form h2")).to_have_text("Rejestracja do udziału w projekcie Baza Trainee Ukraine")
    page.screenshot(path="mwpl_screenshots/titlemw.png")


def test_select_specialization_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.locator("label").filter(has_text="UI/UX Designer").check()
    expect(page.locator("label").filter(has_text="UI/UX Designer")).to_be_checked()
    page.locator("label").filter(has_text="Frontend").check()
    expect(page.locator("label").filter(has_text="Frontend")).to_be_checked()
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    expect(page.locator("label").filter(has_text="QA Manual Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Backend").check()
    expect(page.locator("label").filter(has_text="Backend")).to_be_checked()
    page.locator("label").filter(has_text="Fullstack Engineer").check()
    expect(page.locator("label").filter(has_text="Fullstack Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Project Manager").check()
    expect(page.locator("label").filter(has_text="Project Manager")).to_be_checked()


def test_select_availability_of_experience_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.locator("label").filter(has_text="Więc").check()
    expect(page.locator("label").filter(has_text="Więc")).to_be_checked()
    page.screenshot(path="mwpl_screenshots/yesexp.png")
    page.locator("label").filter(has_text=re.compile(r"^Nie$")).check()
    expect(page.locator("label").filter(has_text=re.compile(r"^Nie$"))).to_be_checked()
    page.screenshot(path="mwpl_screenshots/noexp.png")


def test_select_questionnaire_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.locator("label").filter(has_text="Na stronie Bazy Trainee Ukraina").check()
    expect(page.locator("label").filter(has_text="Na stronie Bazy Trainee Ukraina")).to_be_checked()
    page.locator("label").filter(has_text="Na stronie Bazy Educat na Instagramie").check()
    expect(page.locator("label").filter(has_text="Na stronie Bazy Educat na Instagramie")).to_be_checked()
    page.locator("label").filter(has_text="Na stronie Bazy Edukacyjnej na Facebooku").check()
    expect(page.locator("label").filter(has_text="Na stronie Bazy Edukacyjnej na Facebooku")).to_be_checked()
    page.locator("label").filter(has_text="na kanale Baza Go Telegram").check()
    expect(page.locator("label").filter(has_text="na kanale Baza Go Telegram")).to_be_checked()
    page.locator("label").filter(has_text="w poście na LinkedIn").check()
    expect(page.locator("label").filter(has_text="w poście na LinkedIn")).to_be_checked()


def test_rules_BazaTrainee_project_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_role("button", name="przeczytaj tutaj").click()
    expect(page.locator("//div[@class='ModalDocumentPdf_wrapper___sx__']")).to_be_visible()
    page.screenshot(path="mwpl_screenshots/rules.png")
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    expect(page.locator("//div[@class='ModalDocumentPdf_wrapper___sx__']")).to_be_hidden()
    page.screenshot(path="mwpl_screenshots/closerulesmw.png")


def test_select_agreement_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.locator("label").filter(has_text="Zgadzam się").check()
    page.locator("label").filter(has_text="Wyrażam zgodę na przetwarzanie").check()
    expect(page.locator("label").filter(has_text="Zgadzam się")).to_be_checked()
    expect(page.locator("label").filter(has_text="Wyrażam zgodę na przetwarzanie")).to_be_checked()
    page.screenshot(path="mwpl_screenshots/agreement.png")
    
    
def test_active_send_btn_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_placeholder("Imię").type("Żelisław Andrzej BożenaJózefa")
    page.get_by_placeholder("Nazwisko").type("Żelisław Andrzej BożenaJózefa")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kijów").type("LasławŁukaJózef")
    page.get_by_placeholder("Ukraina").type("LasławŁukaJózef")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link do profilu").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Więc").check()
    page.get_by_placeholder("Twoja odpowiedź").type("test text")
    page.locator("label").filter(has_text="Na stronie Bazy Trainee Ukraina").check()
    page.get_by_role("button", name="przeczytaj tutaj").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    page.locator("label").filter(has_text="Zgadzam się").check()
    page.locator("label").filter(has_text="Wyrażam zgodę na przetwarzanie").check()
    expect(page.get_by_role("button", name="Wysłać")).to_be_enabled()
    page.screenshot(path="mwpl_screenshots/mwsendbtn.png")


def test_send_form_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_placeholder("Imię").type("Żelisław Andrzej BożenaJózefa")
    page.get_by_placeholder("Nazwisko").type("Żelisław Andrzej BożenaJózefa")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kijów").type("LasławŁukaJózef")
    page.get_by_placeholder("Ukraina").type("LasławŁukaJózef")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link do profilu").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Więc").check()
    page.get_by_placeholder("Twoja odpowiedź").type("test text")
    page.locator("label").filter(has_text="Na stronie Bazy Trainee Ukraina").check()
    page.get_by_role("button", name="przeczytaj tutaj").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    page.locator("label").filter(has_text="Zgadzam się").check()
    page.locator("label").filter(has_text="Wyrażam zgodę na przetwarzanie").check()
    page.get_by_role("button", name="Wysłać").click()
    expect(page.locator("div").filter(has_text="Twoje dane zostały pomyślnie").nth(1)).to_be_visible()
    page.screenshot(path="mwpl_screenshots/mwsendform.png")


def test_send_form_without_last_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_placeholder("Imię").type("Żelisław Andrzej BożenaJózefa")
    page.get_by_placeholder("Nazwisko").type("Żelisław Andrzej BożenaJózefa")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kijów").type("LasławŁukaJózef")
    page.get_by_placeholder("Ukraina").type("LasławŁukaJózef")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link do profilu").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Więc").check()
    page.get_by_placeholder("Twoja odpowiedź").type("test text")
    page.locator("label").filter(has_text="Na stronie Bazy Trainee Ukraina").check()
    page.get_by_role("button", name="przeczytaj tutaj").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH ModalDocumentPdf_closeButton__eH4h7']").click()
    page.locator("label").filter(has_text="Zgadzam się").check()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mwpl_screenshots/mwsendwithoutlast.png")


def test_send_form_without_last2_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_placeholder("Imię").type("Żelisław Andrzej BożenaJózefa")
    page.get_by_placeholder("Nazwisko").type("Żelisław Andrzej BożenaJózefa")
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kijów").type("LasławŁukaJózef")
    page.get_by_placeholder("Ukraina").type("LasławŁukaJózef")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link do profilu").type("https://www.linkedin.com/in/test")
    page.locator("label").filter(has_text="Więc").check()
    page.get_by_placeholder("Twoja odpowiedź").type("test text")
    page.locator("label").filter(has_text="Na stronie Bazy Trainee Ukraina").check()
    page.locator("label").filter(has_text="Wyrażam zgodę na przetwarzanie").check()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mwpl_screenshots/mwsendwithoutlast2.png")


def test_empty_form_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_placeholder("Imię").click()
    page.get_by_placeholder("Nazwisko").click()
    page.get_by_placeholder("email@gmail.com").click()
    page.get_by_placeholder("+380 xx xxx xx xx").click()
    page.get_by_placeholder("Kijów").click()
    page.get_by_placeholder("Ukraina").click()
    page.locator("//input[@id='discord']").click()
    page.get_by_placeholder("Link do profilu").click()
    page.get_by_placeholder("Twoja odpowiedź").click()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mwpl_screenshots/mwemptyform.png")


def test_send_form_without_checkbox_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.get_by_role("banner").get_by_role("link", name="Praktyka").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Dołącz do projektu").first.click()
    page.get_by_placeholder("Imię").type("Żelisław Andrzej BożenaJózefa")
    page.get_by_placeholder("Nazwisko").type("Żelisław Andrzej BożenaJózefa")
    page.get_by_placeholder("email@gmail.com").fill("pryvit@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.get_by_placeholder("Kijów").type("LasławŁukaJózef")
    page.get_by_placeholder("Ukraina").type("LasławŁukaJózef")
    page.locator("//input[@id='discord']").type("test")
    page.get_by_placeholder("Link do profilu").type("https://www.linkedin.com/in/test")
    page.get_by_placeholder("Twoja odpowiedź").type("test text")
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mwpl_screenshots/mwsendwithoutcheckbox.png")