import re
from playwright.sync_api import Page, expect


def test_send_form_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Świętosław Róża")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/unittestpl")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="Wyrażam zgodę na").locator("use").click()
    page.get_by_role("button", name="Wysłać").click()
    expect(page.locator("div").filter(has_text="Twoje dane zostały pomyślnie").nth(1)).to_be_visible()
    page.screenshot(path="mw_mentorpl_scr/mwsendform.png")


def test_close_success_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Świętosław Róża")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/unittestpl")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="Wyrażam zgodę na").locator("use").click()
    page.get_by_role("button", name="Wysłać").click()
    page.screenshot(path="mw_mentorpl_scr/mwclosesmwO.png")
    page.locator("//button[@class='CloseBtn_btn__ij9AH UseAlert_close_btn__JJTAr']").click()
    expect(page.locator("div").filter(has_text="Twoje dane zostały pomyślnie").nth(1)).to_be_hidden()
    page.screenshot(path="mw_mentorpl_scr/mwclosesmwC.png")


def test_active_sendbtn_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Świętosław Róża")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/unittestpl")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="Wyrażam zgodę na").locator("use").click()
    expect(page.get_by_role("button", name="Wysłać")).to_be_enabled()
    page.screenshot(path="mw_mentorpl_scr/mwasendbtn.png")


def test_hover_sendbtn_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Świętosław Róża")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/unittestpl")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="Wyrażam zgodę na").locator("use").click()
    page.get_by_role("button", name="Wysłać").hover()
    expect(page.get_by_role("button", name="Wysłać")).to_be_enabled()
    page.screenshot(path="mw_mentorpl_scr/mwhsendbtn.png")


def test_default_sendbtn_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mw_mentorpl_scr/mwdefsendbtn.png")


def test_disabled_sendbtn_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Ś")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/Unittestpl")
    page.get_by_text("-15.00").click()
    page.locator("label").filter(has_text="Wyrażam zgodę na").locator("use").click()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mw_mentorpl_scr/mwdsendbtn.png")


def test_without_checkbox_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Świętosław Róża")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/Unittestpl")
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mw_mentorpl_scr/mwwithoutch.png")


def test_empty_form_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).click()
    page.get_by_placeholder("Nazwisko").click()
    page.get_by_role("textbox", name="email@gmail.com").click()
    page.get_by_placeholder("+380 xx xxx xx xx").click()
    page.locator("//input[@id='discord']").click()
    page.get_by_placeholder("Link do profilu").click()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mw_mentorpl_scr/mwemptyform.png")


def test_title_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    expect(page.locator("//div[@class='RegistrationFormModal_wrapper__bgALB']//h2")).to_have_text("Rejestracja mentora na Baza Trainee Ukraine")
    page.screenshot(path="mw_mentorpl_scr/mwtitle.png")


def test_close_mw_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    expect(page.locator(".RegistrationFormModal_wrapper__bgALB")).to_be_visible()
    page.screenshot(path="mw_mentorpl_scr/mwclosevmwO.png")
    page.locator("//button[@class='CloseBtn_btn__ij9AH RegistrationFormModal_closeButton__Wn1pT']").click()
    expect(page.locator("//div[@class='RegistrationFormModal_wrapper__bgALB']")).to_be_hidden()
    page.screenshot(path="mw_mentorpl_scr/mwclosehmwC.png")


def test_chb_specialization_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.locator("label").filter(has_text="UI/UX Designer").check()
    expect(page.locator("label").filter(has_text="UI/UX Designer")).to_be_checked()
    page.locator("label").filter(has_text="Frontend").check()
    expect(page.locator("label").filter(has_text="Frontend")).to_be_checked()
    page.locator("label").filter(has_text="QA Manual Engineer").check()
    expect(page.locator("label").filter(has_text="QA Manual Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Backend").check()
    expect(page.locator("label").filter(has_text="Backend")).to_be_checked()
    page.locator("label").filter(has_text="Fullstack Engineer").check()
    expect(page.locator("label").filter(has_text="Fullstack Engineer")).to_be_checked()
    page.locator("label").filter(has_text="Project Manager").check()
    expect(page.locator("label").filter(has_text="Project Manager")).to_be_checked()


def test_chb_consultation_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.locator("label").filter(has_text="-15.00").check()
    expect(page.locator("label").filter(has_text="-15.00")).to_be_checked()
    page.locator("label").filter(has_text="-18.00").check()
    expect(page.locator("label").filter(has_text="-18.00")).to_be_checked()
    page.locator("label").filter(has_text="-21.00").check()
    expect(page.locator("label").filter(has_text="-21.00")).to_be_checked()
    page.locator("label").filter(has_text="kiedykolwiek").check()
    expect(page.locator("label").filter(has_text="kiedykolwiek")).to_be_checked()


def test_send_form_without_agreement_pl(page: Page) -> None:
    page.goto("/")
    page.get_by_label("для зміни мови сторінки. вибрана мова").click()
    page.get_by_text("PL").click()
    page.locator("//button[@class='CloseBtn_btn__ij9AH CookiesModal_close__tvIj3']").click()
    page.get_by_role("button", name="Zostać mentorem").click()
    page.get_by_role("textbox", name="Imię", exact=True).type("Świętosław Róża")
    page.get_by_placeholder("Nazwisko").type("Świętosław Róża")
    page.get_by_text("QA Manual Engineer").click()
    page.get_by_role("textbox", name="email@gmail.com").type("test@gmail.com")
    page.get_by_placeholder("+380 xx xxx xx xx").type("999999999")
    page.locator("//input[@id='discord']").type("unittestpl")
    page.get_by_placeholder("Link do profilu").fill("https://www.linkedin.com/in/unittestpl")
    page.get_by_text("-15.00").click()
    expect(page.get_by_role("button", name="Wysłać")).to_be_disabled()
    page.screenshot(path="mw_mentorpl_scr/mwsendformwithoutagr.png")